# Generated by Django 2.1.7 on 2019-02-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggdriveAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='representations',
            new_name='contents',
        ),
    ]
